### ISSUE TITLE
`tibble()` -> `define_enroll()` or `define_fail()`?

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/simtrial#109]
Shall we switch from
```
gs_design_ahr(
  enroll_rate = tibble(duration = ..., rate = ...), 
  fail_rate = tibble.(duration =..., fail_rate = ..., hr = ..., dropout_rate = ...))
```
to
 ```
gs_design_ahr(
  enroll_rate = define_enroll_rate(duration = ..., rate = ...), 
  fail_rate = define_fail_rate.(duration =..., fail_rate = ..., hr = ..., dropout_rate = ...))
```
for consistency with gsDesign2?

**Comment by nanxstats** [comment]
I agree that we should use functions instead of tibble calls to construct the inputs.

However, I _think_ it might not be the best idea to have the same function names in simtrial and gsDesign2. From [tidyverse design guide](https://design.tidyverse.org/function-names.html#conflicts):

> You can't expect to avoid conflicts with every existing CRAN package, but you should strive to avoid conflicts with “nearby” packages (i.e. packages that are commonly used with your package).

So the obvious solution is we can either use a different prefix or have a dedicated new namespace to handle the inputs consistently.

**Comment by nanxstats** [comment]
Will implement this in #97 so closing this for now.
