### ISSUE TITLE
Data frame input constructors

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#185]
We need a strategy to create constructors for the data frame inputs.

As gsDesign2 already has some constructor functions, it would be ideal to NOT duplicate things (as that could cause confusion and namespace conflicts). There are two possible ways to make truth from a single source:

- Reuse gsDesign constructors in simtrial (and move gsDesign2 from `Suggests` to `Imports`).
- Create a new infrastructure package for input data types so that simtrial and gsDesign2 can import it and use such functions from there. Similar to the scales for ggplot2 situation.

Need to make a decision on this.

**Comment by keaven** [comment]
Moving towards enforcing consistency seems nice. We just have to ensure we don’t reduce flexibility KeavenOn Dec 22, 2023, at 00:59, Nan Xiao ***@***.***> wrote:﻿
We need a strategy to create constructors for the data frame inputs.
As gsDesign2 already has some constructor functions, it would be ideal to NOT duplicate things (as that could cause confusion and namespace conflicts). There are two possible ways to make truth from a single source:

Reuse gsDesign constructors in simtrial (and move gsDesign2 from Suggests to Imports).
Create a new infrastructure package for input data types so that simtrial and gsDesign2 can import it and use such functions from there. Similar to the scales for ggplot2 situation.

Need to make a decision on this.

**Comment by LittleBeannie** [comment]
As discussed during the group meeting on January 5, 2024, we have decided not to address this issue at the moment and prioritize other sources.
